---
abstract: 'Perl wrapper for the BitTorrent Sync API'
author:
  - 'Erez Schatz <erez.schatz@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-BitTorrentSync
requires:
  JSON: '0'
  LWP::Simple: '0'
version: '0.1'
